# Generated by Django 5.0.2 on 2024-03-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('t-shirt', 'T-SHIRT'), ('hoodie', 'HOODIE')], default='t-shirt', max_length=10),
        ),
    ]
