# Generated by Django 5.0.2 on 2024-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('white', 'White'), ('black', 'White'), ('off-white', 'Off-White'), ('red', 'Red'), ('brown', 'Brown'), ('green', 'Green'), ('yellow', 'Yellow'), ('pink', 'Pink')], default='off-white', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('t-shirt', 'T-Shirt'), ('hoodie', 'Hoodie')], default='t-shirt', max_length=10),
        ),
    ]
