# Generated by Django 5.0.2 on 2024-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_colour_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('off-white', 'Off-White'), ('red', 'Red'), ('brown', 'Brown'), ('green', 'Green'), ('yellow', 'Yellow'), ('pink', 'Pink')], default='off-white', max_length=10),
        ),
    ]
