# Generated by Django 5.0.2 on 2024-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
