# Generated by Django 5.0.2 on 2024-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_design_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
