# Generated by Django 5.0.2 on 2024-04-24 14:15

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.unique_design_image_path),
        ),
    ]
